name: Docker Build and Run

on:
  push:
    tags: '*'

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Docker image
        run: docker build -t niicloudoperation/notebook .

      - name: Run Docker container
        run: docker run -d --name jupyter_lab_container niicloudoperation/notebook

      - name: Verify Docker container is running
        run: docker ps -a

      - name: Stop Docker container
        run: docker stop jupyter_lab_container

      - name: Remove Docker container
        run: docker rm jupyter_lab_container

      - name: Install dependencies And Run Playwright tests
        run: |
          cd ./ui-tests
          npm install
          npx playwright install
          npx playwright test
          cd ..